# Generated by Django 5.1 on 2025-11-13 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('puesto', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_contratacion', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_promo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('codigo_promo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('precio_especial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(default='Activa', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='rfc',
            field=models.CharField(blank=True, help_text='RFC del proveedor (único)', max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(default='Efectivo', max_length=50)),
                ('empleado', models.ForeignKey(blank=True, db_column='fk_id_empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_Pizzeria.empleados')),
                ('producto', models.ForeignKey(blank=True, db_column='fk_id_producto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_Pizzeria.menu')),
                ('promocion', models.ForeignKey(blank=True, db_column='fk_id_promo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_Pizzeria.promociones')),
            ],
        ),
    ]
